Feat/user
startcoriny/CODE-RED pull request #2
Opened 2024-04-03 08:42 UTC by young970319

2024-04-03 09:42 UTC, ooheunda requested changes
먼저, PR 올리실 땐 안 쓰는 코드 블록 주석은 웬만하면 지워주시길 바랍니다. 테스트용 로그들도 테스트 잘 되었다면 지워주시고요, 프리티어 포맷팅도 적용이 안 되고 있는 것 같은데 설정에서 `Editor: Format on save` 체크해주시고 `Editor: Default Formatter` 프리티어로 지정해주세여.

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.controller.ts
> +      const user = await this.authService.login(
엔드포인트랑 함수명 하나로 통일해주시면 좋을 것 같아요!

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.controller.ts
> +      res.send("로그인 성공");
성공시의 메세지는 보내지 않아도 된다고 합니다! 저희 팀노션에 오늘자 마법의 소라고동 확인해주세여😊

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.service.ts
> +        if(phone_number[3] !== "-" || phone_number[8] !== "-"){
string으로 받다보니 이걸로는 예외처리가 다 안될 것 같네요, 정규식으로 한 번 해보시면 좋을 것 같아요!

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.service.ts
> +        await this.usersRepository.save(newUser);
컨트롤러에선 해당 메서드를 호출하며 리턴하고 있는데 여기는 리턴값이 없네요?

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.service.ts
> +          throw new Error("유저가 존재하지 않습니다.");
NotFoundException 던져주세요. if문 조건식도 lodash 사용하시거나 `!user`로 하시면 좋을 것 같습니다.

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.service.ts
> +          throw new Error('비밀번호를 확인해주세요.');
UnauthorizedException 던져주시면 됩니다. 기본 에러 객체는 지양해주세여~!!

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.service.ts
> +          access_token: this.jwtService.sign(payload),
정의하신 `signToken` 메서드와 같은 동작을 하고 있는 것 같아요.

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.service.ts
> +      }
`UserService`의 `getUserByEmail` 메서드와 동일한 코드입니다. 하나는 지우셔야 할 것 같아요.

2024-04-03 09:42 UTC, ooheunda commented on src/auth/auth.service.ts
> +            throw new UnauthorizedException('존재하지 않는 사용자입니다.');
존재하지 않는다면 NotFound 입니다~~!

2024-04-03 09:42 UTC, ooheunda commented on src/auth/guard/bearer-token.guard.ts
> +        const result = await this.authService.verifyToken(await token);
재사용성을 위해 `AuthService`에 토큰 관련 메서드를 따로 빼두신 점 너무 좋은 것 같아요!!

2024-04-03 09:42 UTC, ooheunda commented on src/auth/guard/bearer-token.guard.ts
> +        const user = await this.usersService.getUserByEmail(result.email);
email로 유저를 찾는 이 메서드 하나를 사용하기 위해 `UserService`를 DI 해주고 있는데, 의존성이 높아지는 이유 때문에 된다면 낮은 계층 DI가 더 나은 방법이라고 합니다. 내부로직이 길거나 어려운 편도 아니라서 한 번 생각해보시면 좋을 것 같아요~!

2024-04-03 09:42 UTC, ooheunda commented on src/auth/guard/bearer-token.guard.ts
> +                throw new UnauthorizedException('AccessToken 이 아닙니다.')
오타인가요? 이 가드는 이따가 한 번 설명해주시면 좋을 것 같아요! 기본 jwt strategy 적용한 AuthGuard와 어느 부분이 다르고 어떻게 적용하면 좋을지여!

2024-04-03 09:42 UTC, ooheunda commented on src/users/dto/create-user.dto.ts
> +    profile_image : string
프로필 이미지는 제가 올린 #1 PR 참고하셔서 S3로 적용해주시면 댑니다~!

2024-04-03 09:42 UTC, ooheunda commented on src/users/users.service.ts
> +  async createUser(user:Pick<Users, 'email' | 'nickname' | 'password'|'phone_number'>) {
`AuthService`에 회원 가입 코드가 있기도 하고, 해당 메서드는 호출이 안 되고 있어요. 지우는 걸 깜빡하신 것 같습니다.

2024-04-03 09:42 UTC, ooheunda commented on src/users/users.service.ts
> +  return {message:'유저 정보가 수정되었습니다.'}
오잉?

2024-04-03 09:42 UTC, ooheunda commented on src/users/users.service.ts
> +  return {message:'아이디가 삭제되었습니다.'}
raw한 메세지 응답은 지양해주세요. 위에 썼듯이 성공시엔 http status code만 넘겨주어도 무방합니다!

2024-04-03 10:36 UTC, startcoriny commented on src/users/users.service.ts
> +  return {message:'유저 정보가 수정되었습니다.'}
오잉?

2024-04-03 10:39 UTC, startcoriny commented
PR하기 전에 마지막으로 코드 살펴 보면서 사용하지 않는 부분들은 정리해주고 PR한다면 더 좋을 것 같습니다!

2024-04-04 05:13 UTC, ooheunda commented
리뷰 반영 짱입니다...🥹👍

1. repo로도 가능하지만 service 계층을 DI 하는 부분
2. 프로필 이미지 S3 적용 (PR #1 참고)
3. 안 쓰는 가드 삭제 (delete도 커밋을 해주셔야 해요~!)

1은 너무 사소한 부분이라 나중에 해도 될 것 같아요.
2, 3만 적용해서 커밋/푸시 후 머지하시면 될 것 같습니다~!!

2024-04-04 06:12 UTC, boogie-bogie commented
ㅎㄷㄷ.. 멋지십니다 다덜. 여우잉햄 고생 많으셨습니다.

#Review - 기냥저냥 의견입니다!

- bcrypt의 salt도 써보면 어떨까요?

- 휴대폰 번호에서 정규표현식으로 유효성 검사는 Dto쪽에서 하면 어떨까요? 
   @Matches( 정규표현식, {message: "" } ) 이런식으로 쓸 수 있다고 알고 있습니다!

++++ Swagger까지 작성하는 가여우잉??? 완벽하자나~

2024-04-04 07:10 UTC, merged