뉴스 크롤링
startcoriny/CODE-RED pull request #3
Opened 2024-04-03 10:57 UTC by startcoriny

- 의존성 추가: puppeteer-core, natural
- 뉴스 정보를 끌어오기 위한 파일만 따로 만듦
- 뉴스 정보 크롤링 모듈 `news`추가

현재 뉴스를 크롤링 해와서 서울 기준으로 중복되는 뉴스 게시글들 전부 제외하고 최대한 필터 해서 정보를 띄우고 가져와서 데이터 베이스에 저장까지 완료 했습니다.
뉴스를 크롤링하면서 조회까지하면 너무 시간이 오래 걸려 클라이언트 입장에서 생각했을 때 정보만 보게 하는게 맞는것 같아 api를 `saveNews`, `getNews`두개로 나눴습니다.

따로 설정해야 하는 env파일 같은 건 없습니다.
다만 동일한 데이터를 받아왔을때 새로운 데이터만 받는 로직은 다시 짜야 할것 같습니다...ㅠㅠ

2024-04-03 16:07 UTC, ooheunda requested changes
새로운 기술 하시느라 고생 많으셨습니다! 역쉬 갓곽.

2024-04-03 16:07 UTC, ooheunda commented on src/news/news.service.ts
> +      }
이 부분이 수정할 로직인거죠? 👍

2024-04-03 16:07 UTC, ooheunda commented on src/news/news.service.ts
> +      console.error(e);
e...

2024-04-03 16:07 UTC, ooheunda commented on src/news/news.service.ts
> +  async getNews() {
유저가 뉴스 목록 조회하고 누르면 url로 이동하게 하는 거 맞나오? (이동은 단순하니 FE에서?)
페이지네이션이 필요해보입니다!

2024-04-04 05:10 UTC, ooheunda commented
수정 잘 된 것 같아요! 소라고동 업데이트 된 것도 봤습니다. (저도 데려가주시지...🥹)
이제 머지하시면 될 것 같아여 너무 고생하셨습니다!

2024-04-04 05:23 UTC, startcoriny commented
다음엔 데려가드리겠습니다!

2024-04-04 05:23 UTC, merged